-- AlterTable
ALTER TABLE `character_data` ADD COLUMN `energy` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `health` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxEnergy` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxHealth` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxMana` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxMelee` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `maxUltimate` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `ultimate` INTEGER NOT NULL DEFAULT 0;
